### PR TITLE
when %use shift kernel type, fix the kernel type of the next cell #187

### PR DESCRIPTION
**Pull request by jma7**
A fix for %use problem.

### CODE REVIEW

**Comment by BoPeng** [comment]
does this handle the case when you run 

```
%use R
```
with `Ctrl-Enter` so no new cell is created, and there might be no new cell (if this cell is the last)?

**Comment by jma7** [comment]
Just added a  check for Ctrl-Enter.

**Comment by BoPeng** [comment]
This does not really fix the issue, right? Basically, you are changing the kernel of the next empty cell, which can  pre-exist, in which case the cell should not be touched with either C-Enter or S-Enter. 

So let us see,

1. Shift-Enter at the last cell, this will work.
2. Shift-Enter not at the last cell, no new cell will be inserted, this will change the next empty cell, wrong.
3. Ctrl-Enter at the last cell, your second patch fixes it.
4. Ctrl-Enter not at the last cell, no new cell will be inserted, this will change the next empty cell.

So 
1. Can you limit the patch only to `S-Enter`? This will fix 4.
2. If you can do 1, you can check if the cell if the second last one to decide if a new cell has been inserted.

**Comment by jma7** [comment]
I assume the next empty cell needs to be changed to the same kernel in 2, so the empty cell should stay the same as before?

**Comment by BoPeng** [comment]
When there is an existing cell after the current cell, Shift-Enter will not create a new cell so the kernel of that cell should not be changed regardless if the existing cell is empty or not. That is to say, we should only change kernel of new cell, which happens only with Shift-Enter of the last cell of a notebook.

**Pull request merged**
